service: swapi-api-serverless-dynamodb

useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: "us-east-1"
  environment:
    CHARACTERS_TABLE: "characters"
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.CHARACTERS_TABLE}"

resources:
  Resources:
    CharacterTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: characterId
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: characterId
            KeyType: HASH
        TableName: ${self:provider.environment.CHARACTERS_TABLE}

functions:
  getCharactersSwapi:
    handler: src/application/controllers/character/swapi/getCharactersController.handler
    events:
      - httpApi:
          method: GET
          path: /swapi/characters/{page}
  getCharactersApi:
    handler: src/application/controllers/character/api/getCharactersController.handler
    events:
      - httpApi:
          method: GET
          path: /api/characters

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    target: node16

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dynamodb-local
