openapi: 3.0.3
info:
  title: API de Star Wars
  version: 1.0.0
paths:
  /:
    post:
      summary: Crear un personaje (character)
      operationId: createCharacter
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Nombre del personaje
                height:
                  type: string
                  description: Altura del personaje
                mass:
                  type: string
                  description: Peso del personaje
                hair_color:
                  type: string
                  description: Color de cabello del personaje
                skin_color:
                  type: string
                  description: Color de piel del personaje
                eye_color:
                  type: string
                  description: Color de ojos del personaje
                birth_year:
                  type: string
                  description: Año de nacimiento del personaje
                gender:
                  type: string
                  description: Genero del personaje
                homeworld:
                  type: array
                  description: Mundo natal del personaje
                films:
                  type: array
                  description: Peliculas en las que aparece del personaje
                species:
                  type: array
                  description: Especies del personaje
                vehicles:
                  type: array
                  description: Vehiculos manejados por el personaje
                starships:
                  type: array
                  description: Naves estelares pilotadas por el personaje
                created:
                  type: string
                  description: Fecha de creacion del personaje
                edited:
                  type: string
                  description: Fecha de edicion del personaje
                url:
                  type: string
                  description: URL para ver mas datos del personaje
                biography:
                  type: string
                  description: Descripción o biografía del personaje

              example:
                name: "Luke Skywalker"
                height: "150"
                mass: "49"
                hair_color: "brown"
                skin_color: "light"
                eye_color: "brown"
                birth_year: "19BBY"
                gender: "male"
                homeworld: ["https://swapi.py4e.com/api/planets/2/"]
                films:
                  [
                    "https://swapi.py4e.com/api/films/1/",
                    "https://swapi.py4e.com/api/films/2/",
                    "https://swapi.py4e.com/api/films/3/",
                    "https://swapi.py4e.com/api/films/6/",
                    "https://swapi.py4e.com/api/films/7/",
                  ]
                species: ["https://swapi.py4e.com/api/species/1/"]
                vehicles: ["https://swapi.py4e.com/api/vehicles/30/"]
                starships: []
                created: "2014-12-10T15:20:09.791000Z"
                edited: "2014-12-20T21:17:50.315000Z"
                url: "https://swapi.py4e.com/api/people/1/"
                biography: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
      responses:
        "201":
          description: Biografía creada con éxito
          content:
            application/json:
              schema:
                type: object
                properties:
                  characterId:
                    type: string
                    description: ID de la biografia en dynamoDB (uuid) que ya existe
                  nombre:
                    type: string
                    description: Nombre del personaje
                  altura:
                    type: string
                    description: Altura del personaje
                  masa:
                    type: string
                    description: Peso del personaje
                  color_cabello:
                    type: string
                    description: Color de cabello del personaje
                  color_piel:
                    type: string
                    description: Color de piel del personaje
                  color_ojo:
                    type: string
                    description: Color de ojos del personaje
                  fecha_nacimiento:
                    type: string
                    description: Año de nacimiento del personaje
                  genero:
                    type: string
                    description: Genero del personaje
                  mundo_natal:
                    type: array
                    description: Mundo natal del personaje
                  peliculas:
                    type: array
                    description: Peliculas en las que aparece del personaje
                  especies:
                    type: array
                    description: Especies del personaje
                  vehiculos:
                    type: array
                    description: Vehiculos manejados por el personaje
                  naves_estelares:
                    type: array
                    description: Naves estelares pilotadas por el personaje
                  creado:
                    type: string
                    description: Fecha de creacion del personaje
                  editado:
                    type: string
                    description: Fecha de edicion del personaje
                  url:
                    type: string
                    description: URL para ver mas datos del personaje
                  biografia:
                    type: string
                    description: Descripción o biografía del personaje
                  idSwapi:
                    type: string
                    description: Id del personaje dentro de Swapi
              example:
                id: "c771efe8-f664-4d5d-80a8-a1ef9447cd75"
                nombre: "Luke Skywalker"
                altura: "150"
                masa: "49"
                color_cabello: "blond"
                color_piel: "fair"
                color_ojo: "blue"
                fecha_nacimiento: "19BBY"
                genero: "male"
                mundo_natal: ["https://swapi.py4e.com/api/planets/2/"]
                peliculas:
                  [
                    "https://swapi.py4e.com/api/films/1/",
                    "https://swapi.py4e.com/api/films/2/",
                    "https://swapi.py4e.com/api/films/3/",
                    "https://swapi.py4e.com/api/films/6/",
                    "https://swapi.py4e.com/api/films/7/",
                  ]
                especies: ["https://swapi.py4e.com/api/species/1/"]
                vehiculos:
                  [
                    "https://swapi.py4e.com/api/vehicles/14/",
                    "https://swapi.py4e.com/api/vehicles/30/",
                  ]
                naves_estelares:
                  [
                    "https://swapi.py4e.com/api/starships/12/",
                    "https://swapi.py4e.com/api/starships/22/",
                  ]
                creado: "2014-12-10T15:20:09.791000Z"
                editado: "2014-12-20T21:17:50.315000Z"
                url: "https://swapi.py4e.com/api/people/1/"
                biografia: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
                idSwapi: "1"
        "200":
          description: Biografía ya existe
          content:
            application/json:
              schema:
                type: object
                properties:
                  characterId:
                    type: string
                    description: ID de la biografia en dynamoDB (uuid) que ya existe
                  nombre:
                    type: string
                    description: Nombre del personaje
                  altura:
                    type: string
                    description: Altura del personaje
                  masa:
                    type: string
                    description: Peso del personaje
                  color_cabello:
                    type: string
                    description: Color de cabello del personaje
                  color_piel:
                    type: string
                    description: Color de piel del personaje
                  color_ojo:
                    type: string
                    description: Color de ojos del personaje
                  fecha_nacimiento:
                    type: string
                    description: Año de nacimiento del personaje
                  genero:
                    type: string
                    description: Genero del personaje
                  mundo_natal:
                    type: array
                    description: Mundo natal del personaje
                  peliculas:
                    type: array
                    description: Peliculas en las que aparece del personaje
                  especies:
                    type: array
                    description: Especies del personaje
                  vehiculos:
                    type: array
                    description: Vehiculos manejados por el personaje
                  naves_estelares:
                    type: array
                    description: Naves estelares pilotadas por el personaje
                  creado:
                    type: string
                    description: Fecha de creacion del personaje
                  editado:
                    type: string
                    description: Fecha de edicion del personaje
                  url:
                    type: string
                    description: URL para ver mas datos del personaje
                  biografia:
                    type: string
                    description: Descripción o biografía del personaje
                  idSwapi:
                    type: string
                    description: Id del personaje dentro de Swapi
              example:
                id: "88727577-6257-4a92-9682-f9e218edffde"
                nombre: "Leia Organa"
                altura: "150"
                masa: "49"
                color_cabello: "brown"
                color_piel: "light"
                color_ojo: "brown"
                fecha_nacimiento: "19BBY"
                genero: "female"
                mundo_natal: "https://swapi.py4e.com/api/planets/2/"
                peliculas:
                  [
                    "https://swapi.py4e.com/api/films/1/",
                    "https://swapi.py4e.com/api/films/2/",
                    "https://swapi.py4e.com/api/films/3/",
                    "https://swapi.py4e.com/api/films/6/",
                    "https://swapi.py4e.com/api/films/7/",
                  ]
                especies: ["https://swapi.py4e.com/api/species/1/"]
                vehiculos: ["https://swapi.py4e.com/api/vehicles/30/"]
                naves_estelares: []
                creado: "2014-12-10T15:20:09.791000Z"
                editado: "2014-12-20T21:17:50.315000Z"
                url: "https://swapi.py4e.com/api/people/5/"
                biografia: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                idSwapi: "5"
    get:
      summary: Obtener información de la biografía y personajes
      operationId: getBiography
      responses:
        "200":
          description: Información de la biografía recuperada con éxito
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: ID del personaje
                    nombre:
                      type: string
                      description: Nombre del personaje
                    altura:
                      type: string
                      description: Altura del personaje
                    peso:
                      type: string
                      description: Peso del personaje
                    color_cabello:
                      type: string
                      description: Color de cabello del personaje
                    color_piel:
                      type: string
                      description: Color de piel del personaje
                    color_ojos:
                      type: string
                      description: Color de ojos del personaje
                    fecha_nacimiento:
                      type: string
                      description: Año de nacimiento del personaje
                    genero:
                      type: string
                      description: Género del personaje
                    planetaNatal:
                      type: string
                      description: Planeta natal del personaje
                    peliculas:
                      type: string
                      description: Peliculas en las que aprece el personaje
                    especies:
                      type: string
                      description: Especie del personaje
                    vehiculos:
                      type: string
                      description: Vehiculos que conduce el personaje
                    navesEspaciales:
                      type: string
                      description: Naves espaciales que conduce el personaje
                    biografia:
                      type: string
                      description: Descripción o biografía del personaje
              example:
                - id: 1
                  nombre: "Luke Skywalker"
                  altura: "172"
                  peso: "77"
                  color_cabello: "blond"
                  color_piel: "fair"
                  color_ojos: "blue"
                  fecha_nacimiento: "19BBY"
                  genero: "male"
                  planetaNatal: "Tatooine"
                  peliculas:
                    [
                      "A New Hope",
                      "The Empire Strikes Back",
                      "Return of the Jedi",
                      "Revenge of the Sith",
                      "The Force Awakens",
                    ]
                  especies: ["Human"]
                  vehiculos:
                    [
                      "https://swapi.py4e.com/api/vehicles/14/",
                      "https://swapi.py4e.com/api/vehicles/30/",
                    ]
                  navesEspaciales:
                    [
                      "https://swapi.py4e.com/api/starships/12/",
                      "https://swapi.py4e.com/api/starships/22/",
                    ]
                  biografia: "Luke Skywalker es un personaje ficticio y el protagonista​ de la trilogía original de la saga de ciencia ficción Star Wars.​ Procedente de la colonia de asteroides de Polis Massa, es el único hijo varón de Anakin Skywalker y la senadora Padmé Amidala."
  /swapi/characters/{page}:
    get:
      summary: Obtener información de los personajes de SWAPI
      operationId: getCharactersFromApi
      parameters:
        - name: page
          in: path
          required: true
          description: Número de página de personajes de SWAPI
          schema:
            type: integer
      responses:
        "200":
          description: Información de los personajes recuperada con éxito
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: ID del personaje
                  nombre:
                    type: string
                    description: Nombre del personaje
                  altura:
                    type: string
                    description: Altura del personaje
                  peso:
                    type: string
                    description: Peso del personaje
                  color_cabello:
                    type: string
                    description: Color de cabello del personaje
                  color_piel:
                    type: string
                    description: Color de piel del personaje
                  color_ojos:
                    type: string
                    description: Color de ojos del personaje
                  fecha_nacimiento:
                    type: string
                    description: Año de nacimiento del personaje
                  genero:
                    type: string
                    description: Género del personaje
                  planetaNatal:
                    type: string
                    description: Planeta natal del personaje
                  peliculas:
                    type: string
                    description: Peliculas en las que aprece el personaje
                  especies:
                    type: string
                    description: Especie del personaje
                  vehiculos:
                    type: string
                    description: Vehiculos que conduce el personaje
                  navesEspaciales:
                    type: string
                    description: Naves espaciales que conduce el personaje
              example:
                id: "1"
                nombre: "Luke Skywalker"
                altura: "172"
                peso: "77"
                color_cabello: "blond"
                color_piel: "fair"
                color_ojos: "blue"
                fecha_nacimiento: "19BBY"
                genero: "male"
                planetaNatal: "Tatooine"
                peliculas:
                  [
                    "A New Hope",
                    "The Empire Strikes Back",
                    "Return of the Jedi",
                    "Revenge of the Sith",
                    "The Force Awakens",
                  ]
                especies: ["Human"]
                vehiculos:
                  [
                    "https://swapi.py4e.com/api/vehicles/14/",
                    "https://swapi.py4e.com/api/vehicles/30/",
                  ]
                navesEspaciales:
                  [
                    "https://swapi.py4e.com/api/starships/12/",
                    "https://swapi.py4e.com/api/starships/22/",
                  ]
